language: objective-c
osx_image: xcode7.3
xcode_project: Torch.xcodeproj
xcode_scheme: Torch
xcode_sdk: macosx

before_script:
    - gem install cucumber --no-rdoc --no-ri
    - gem install aruba --no-rdoc --no-ri

script:
    - cd Generator
    - bash run_tests.sh
    - cd ..
    - travis_wait xcodebuild -workspace Torch.xcworkspace -scheme Torch -sdk macosx clean test

after_script:
    - sleep 5
