#!/usr/bin/env bash

FILE_NAME=torch_generator.app
cd Generator
env -i PATH=${PATH}, HOME=${HOME} xcodebuild -project 'TorchGenerator.xcodeproj' -scheme 'TorchGenerator' -configuration 'Release' CONFIGURATION_BUILD_DIR=$(pwd)/Build clean build
mv Build/torch.app ../$FILE_NAME
cd ..

# $FILE_PATH/Contents/MacOS/torch "$@"
