included:
    - Sources

# rule identifiers to exclude from running
disabled_rules:
    - valid_docs
    - function_body_length
    - cyclomatic_complexity
    - variable_name

# some rules are only opt-in
opt_in_rules:
    - empty_count

# configurable rules can be customized from this configuration file
line_length: 200
